[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/stretch3_zmq_core"]

[project]
name = "stretch3-zmq-core"
version = "0.0.3"
requires-python = ">=3.12, <3.13"
dependencies = [
    "pydantic==2.10.6",
    "msgpack>=1.1.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.4",
    "mypy>=1.10",
]
